general:
    seed: 0
model:
    d_model: 1024
    n_heads: 4
    seq_len: 4096
    n_persist: 128
    n_mem_tokens: 128
    mem_hidden: 4
    chunk_size: 256
    weight_decay_memory: 0.01
    momentum_memory: 0.9
optimizer:
    opt_learning_rate: 0.0004
    opt_weight_decay: 0.1
training:
    batch_size: 8
    max_steps: 600000
